[project]
name = "fast-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datetime>=5.5",
    "fastapi[standard]>=0.116.2",
    "pydantic>=2.11.9",
    "requests>=2.32.5",
    "uvicorn[standard]>=0.35.0",
]
